version: '2.4'
services:
  wwwserver:
    build: .
    image: asn/phpwebapp
    ports:
      # Random external port for HTTP direct access 
      - "80"
    scale: 4
    mem_limit: 50m
    mem_reservation: 25m
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mariadb 
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=notesdb
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=secreto
      # Descomentar si hay problemas para incializar la BD de pruebas
      # https://github.com/docker-library/mariadb/issues/160#issuecomment-528393445
#     - MYSQL_INIT_SKIP_TZINFO=1
    ports:
      - 3306:3306
  haproxy:
    image: asn/haproxy
    build: haproxy/
    ports:
      - "8081:80"
    volumes:
      # HAProxy static config file
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg 
